/*
 * Conformal Prediction Log D
 * This is a Conformal Prediction Service for predicting Log D values for compounds. The  underlying model has been trained and evaluated on ChEMBL 23 data. Modeling is done using CPSign, product of GenettaSoft AB.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@genettasoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.uu.farmbio.api.model;

import java.util.Objects;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.ws.rs.core.Response.Status;

import org.json.simple.JSONObject;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ErrorResponse
 */
//@ApiModel(description = "ErrorResponse")
public class ErrorResponse {
	
	@JsonProperty("code")
//	@ApiModelProperty(required = true, value = "HTTP status code", example="400")
	@Min(100)
	@Max(600)
	private final Integer code;

	@JsonProperty("message")
//	@ApiModelProperty(required = true, value = "ErrorResponse message", example="Invalid argument")
	private final String message;
	
	public ErrorResponse(Status status, String message) {
		this.code = status.getStatusCode();
		this.message = message;
	}
	
	public ErrorResponse(Integer code, String message) {
		this.code = code;
		this.message = message;
	}
	
	public int getCode() {
		return code;
	}

	public String getMessage() {
		return message;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ErrorResponse error = (ErrorResponse) o;
		return Objects.equals(this.code, error.code) &&
				Objects.equals(this.message, error.message);
	}

	@Override
	public int hashCode() {
		return Objects.hash(code, message);
	}

	@SuppressWarnings("unchecked")
	public JSONObject toJSON(){
		JSONObject res = new JSONObject();
		res.put("code", code);
		res.put("message", message);
		return res;
	}

	@Override
	public String toString() {
		return toJSON().toJSONString();
	}
	
}

